
// JavaScript код для отображения диаграмм товарных портфелей по коэффициенту Шарпа
document.addEventListener("DOMContentLoaded", function() {
    const container = document.getElementById("charts-container");
    var header = document.createElement("p");
    header.innerHTML = "<strong>За месяц (начало: 2024-12-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_1m.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_1m.png";
    img.alt = "commodity_portfolio_value_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_1m.png";
    img.alt = "commodity_portfolio_parts_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За квартал (начало: 2024-10-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_1q.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_1q.png";
    img.alt = "commodity_portfolio_value_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_1q.png";
    img.alt = "commodity_portfolio_parts_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За полгода (начало: 2024-07-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_y2.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_y2.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_y2.png";
    img.alt = "commodity_portfolio_value_y2.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_y2.png";
    img.alt = "commodity_portfolio_parts_y2.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За год (начало: 2024-01-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_1y.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_1y.png";
    img.alt = "commodity_portfolio_value_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_1y.png";
    img.alt = "commodity_portfolio_parts_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За два года (начало: 2023-01-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_2y.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_2y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_2y.png";
    img.alt = "commodity_portfolio_value_2y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_2y.png";
    img.alt = "commodity_portfolio_parts_2y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За три года (начало: 2022-01-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_3y.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_3y.png";
    img.alt = "commodity_portfolio_value_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_3y.png";
    img.alt = "commodity_portfolio_parts_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За пять лет (начало: 2020-01-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_5y.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_5y.png";
    img.alt = "commodity_portfolio_value_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_5y.png";
    img.alt = "commodity_portfolio_parts_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За десять лет (начало: 2015-01-04)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_sharp_risk_doh_10y.png";
    img.alt = "commodity_portfolio_sharp_risk_doh_10y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_value_10y.png";
    img.alt = "commodity_portfolio_value_10y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/commodity_portfolio_parts_10y.png";
    img.alt = "commodity_portfolio_parts_10y.png";
    img.style.width = "100%";
    container.appendChild(img);

});
