
// JavaScript код для отображения диаграмм валютных портфелей по коэффициенту Шарпа
document.addEventListener("DOMContentLoaded", function() {
    const container = document.getElementById("charts-container");
    var header = document.createElement("p");
    header.innerHTML = "<strong>За месяц (начало: 2025-09-30)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_1m.png";
    img.alt = "currency_sharp_risk_return_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_1m.png";
    img.alt = "currency_sharp_value_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_1m.png";
    img.alt = "currency_sharp_parts_1m.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CNY">CNY (Китайский юань)</a> - 35.85%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=QAR">QAR (Катарский риал)</a> - 10.62%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CZK">CZK (Чешская крона)</a> - 7.51%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ZAR">ZAR (Южноафриканский рэнд)</a> - 7.43%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PLN">PLN (Польский злотый)</a> - 4.81%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KRW">KRW (Южнокорейская вона)</a> - 4.08%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=INR">INR (Индийская рупия)</a> - 3.58%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=GBP">GBP (Фунт стерлингов)</a> - 2.81%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 2.70%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PHP">PHP (Филиппинское песо)</a> - 2.27%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EUR">EUR (Евро)</a> - 1.95%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 1.82%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ARS">ARS (Аргентинское песо)</a> - 1.75%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CHF">CHF (Швейцарский франк)</a> - 1.66%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=UAH">UAH (Украинская гривна)</a> - 1.44%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За квартал (начало: 2025-07-31)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_1q.png";
    img.alt = "currency_sharp_risk_return_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_1q.png";
    img.alt = "currency_sharp_value_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_1q.png";
    img.alt = "currency_sharp_parts_1q.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=USD">USD (Доллар США)</a> - 5.21%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CNY">CNY (Китайский юань)</a> - 5.07%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EUR">EUR (Евро)</a> - 4.52%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HKD">HKD (Гонконгский доллар)</a> - 4.15%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CZK">CZK (Чешская крона)</a> - 3.72%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=AUD">AUD (Австралийский доллар)</a> - 3.60%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EGP">EGP (Египетский фунт)</a> - 3.51%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PKR">PKR (Пакистанская рупия)</a> - 2.91%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ISK">ISK (Исландская крона)</a> - 2.87%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=IDR">IDR (Индонезийская рупия)</a> - 2.70%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KZT">KZT (Казахстанский тенге)</a> - 2.63%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SGD">SGD (Сингапурский доллар)</a> - 2.63%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HUF">HUF (Венгерский форинт)</a> - 2.58%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SEK">SEK (Шведская крона)</a> - 2.55%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=NOK">NOK (Норвежская крона)</a> - 2.47%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KRW">KRW (Южнокорейская вона)</a> - 2.45%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PHP">PHP (Филиппинское песо)</a> - 2.39%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CLP">CLP (Чилийское песо)</a> - 2.39%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=QAR">QAR (Катарский риал)</a> - 2.35%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 2.33%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PEN">PEN (Перуанский новый соль)</a> - 2.31%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=INR">INR (Индийская рупия)</a> - 2.27%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=BRL">BRL (Бразильский реал)</a> - 2.27%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 2.23%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ARS">ARS (Аргентинское песо)</a> - 2.19%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ILS">ILS (Новый израильский шекель)</a> - 2.17%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MXN">MXN (Мексиканское песо)</a> - 2.04%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PLN">PLN (Польский злотый)</a> - 1.98%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=TWD">TWD (Новый тайваньский доллар)</a> - 1.92%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=THB">THB (Тайский бат)</a> - 1.85%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=JPY">JPY (Японская иена)</a> - 1.79%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=TRY">TRY (Турецкая лира)</a> - 1.65%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ZAR">ZAR (Южноафриканский рэнд)</a> - 1.63%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=UAH">UAH (Украинская гривна)</a> - 1.62%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За год (начало: 2024-10-31)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_1y.png";
    img.alt = "currency_sharp_risk_return_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_1y.png";
    img.alt = "currency_sharp_value_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_1y.png";
    img.alt = "currency_sharp_parts_1y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=AED">AED (Дирхам ОАЭ)</a> - 11.93%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EGP">EGP (Египетский фунт)</a> - 4.60%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MYR">MYR (Малайзийский ринггит)</a> - 4.29%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EUR">EUR (Евро)</a> - 4.04%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ILS">ILS (Новый израильский шекель)</a> - 3.64%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SGD">SGD (Сингапурский доллар)</a> - 3.62%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HUF">HUF (Венгерский форинт)</a> - 3.47%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SEK">SEK (Шведская крона)</a> - 3.38%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HKD">HKD (Гонконгский доллар)</a> - 3.37%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=AUD">AUD (Австралийский доллар)</a> - 3.30%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PEN">PEN (Перуанский новый соль)</a> - 3.25%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CZK">CZK (Чешская крона)</a> - 3.12%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MXN">MXN (Мексиканское песо)</a> - 2.92%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 2.71%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CHF">CHF (Швейцарский франк)</a> - 2.58%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=THB">THB (Тайский бат)</a> - 2.55%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ISK">ISK (Исландская крона)</a> - 2.53%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=NOK">NOK (Норвежская крона)</a> - 2.46%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 2.35%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=BRL">BRL (Бразильский реал)</a> - 2.31%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ARS">ARS (Аргентинское песо)</a> - 2.21%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PHP">PHP (Филиппинское песо)</a> - 2.20%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=TWD">TWD (Новый тайваньский доллар)</a> - 2.07%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CLP">CLP (Чилийское песо)</a> - 1.84%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KRW">KRW (Южнокорейская вона)</a> - 1.52%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KWD">KWD (Кувейтский динар)</a> - 1.51%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CAD">CAD (Канадский доллар)</a> - 1.50%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=JPY">JPY (Японская иена)</a> - 1.48%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=VND">VND (Вьетнамский донг)</a> - 1.47%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=IDR">IDR (Индонезийская рупия)</a> - 1.44%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KZT">KZT (Казахстанский тенге)</a> - 1.40%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За три года (начало: 2022-10-31)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_3y.png";
    img.alt = "currency_sharp_risk_return_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_3y.png";
    img.alt = "currency_sharp_value_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_3y.png";
    img.alt = "currency_sharp_parts_3y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HKD">HKD (Гонконгский доллар)</a> - 12.03%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ILS">ILS (Новый израильский шекель)</a> - 7.82%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MYR">MYR (Малайзийский ринггит)</a> - 6.41%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SGD">SGD (Сингапурский доллар)</a> - 6.05%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CHF">CHF (Швейцарский франк)</a> - 5.55%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PLN">PLN (Польский злотый)</a> - 4.77%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PEN">PEN (Перуанский новый соль)</a> - 4.45%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SAR">SAR (Саудовский риял)</a> - 4.30%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 3.63%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=GBP">GBP (Фунт стерлингов)</a> - 3.38%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ARS">ARS (Аргентинское песо)</a> - 3.36%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EUR">EUR (Евро)</a> - 3.21%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=THB">THB (Тайский бат)</a> - 3.15%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ISK">ISK (Исландская крона)</a> - 3.01%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SEK">SEK (Шведская крона)</a> - 2.80%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CNY">CNY (Китайский юань)</a> - 2.78%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MXN">MXN (Мексиканское песо)</a> - 2.52%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=TWD">TWD (Новый тайваньский доллар)</a> - 2.25%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EGP">EGP (Египетский фунт)</a> - 2.14%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CLP">CLP (Чилийское песо)</a> - 2.09%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PHP">PHP (Филиппинское песо)</a> - 1.97%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 1.80%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HUF">HUF (Венгерский форинт)</a> - 1.58%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За пять лет (начало: 2020-10-31)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_5y.png";
    img.alt = "currency_sharp_risk_return_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_5y.png";
    img.alt = "currency_sharp_value_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_5y.png";
    img.alt = "currency_sharp_parts_5y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SGD">SGD (Сингапурский доллар)</a> - 11.15%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ILS">ILS (Новый израильский шекель)</a> - 7.72%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CHF">CHF (Швейцарский франк)</a> - 6.59%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=AED">AED (Дирхам ОАЭ)</a> - 5.96%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MYR">MYR (Малайзийский ринггит)</a> - 5.87%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=GBP">GBP (Фунт стерлингов)</a> - 5.50%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CZK">CZK (Чешская крона)</a> - 5.31%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SAR">SAR (Саудовский риял)</a> - 5.15%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=USD">USD (Доллар США)</a> - 4.44%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MXN">MXN (Мексиканское песо)</a> - 3.87%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ISK">ISK (Исландская крона)</a> - 3.79%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=QAR">QAR (Катарский риал)</a> - 3.37%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PLN">PLN (Польский злотый)</a> - 3.25%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PEN">PEN (Перуанский новый соль)</a> - 3.09%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 2.97%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=KWD">KWD (Кувейтский динар)</a> - 2.85%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SEK">SEK (Шведская крона)</a> - 2.65%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=BRL">BRL (Бразильский реал)</a> - 2.49%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 2.13%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ZAR">ZAR (Южноафриканский рэнд)</a> - 2.08%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);
    var header = document.createElement("p");
    header.innerHTML = "<strong>За десять лет (начало: 2015-10-31)</strong>";
    container.appendChild(header);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_risk_return_10y.png";
    img.alt = "currency_sharp_risk_return_10y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_value_10y.png";
    img.alt = "currency_sharp_value_10y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var img = document.createElement("img");
    img.src = "https://prog815.github.io/abscur2/contents/currency_sharp_parts_10y.png";
    img.alt = "currency_sharp_parts_10y.png";
    img.style.width = "100%";
    container.appendChild(img);
    var currencyList = document.createElement("p");
    currencyList.innerHTML = "<strong>Топ валют по долям в портфеле:</strong> "; 
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ILS">ILS (Новый израильский шекель)</a> - 8.09%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SAR">SAR (Саудовский риял)</a> - 7.23%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SGD">SGD (Сингапурский доллар)</a> - 7.06%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CZK">CZK (Чешская крона)</a> - 6.00%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=USD">USD (Доллар США)</a> - 5.12%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CHF">CHF (Швейцарский франк)</a> - 5.02%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MYR">MYR (Малайзийский ринггит)</a> - 4.28%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=TWD">TWD (Новый тайваньский доллар)</a> - 4.08%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=THB">THB (Тайский бат)</a> - 3.99%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=HKD">HKD (Гонконгский доллар)</a> - 3.38%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PLN">PLN (Польский злотый)</a> - 3.32%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=MXN">MXN (Мексиканское песо)</a> - 3.25%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=SEK">SEK (Шведская крона)</a> - 3.19%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ZAR">ZAR (Южноафриканский рэнд)</a> - 3.05%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=AED">AED (Дирхам ОАЭ)</a> - 2.79%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=COP">COP (Колумбийское песо)</a> - 2.72%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=GBP">GBP (Фунт стерлингов)</a> - 2.66%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=PEN">PEN (Перуанский новый соль)</a> - 2.65%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=RUB">RUB (Российский рубль)</a> - 2.64%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=ISK">ISK (Исландская крона)</a> - 2.29%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=BRL">BRL (Бразильский реал)</a> - 2.27%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=CLP">CLP (Чилийское песо)</a> - 2.19%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=QAR">QAR (Катарский риал)</a> - 2.14%, `;
    currencyList.innerHTML += `<a href="https://www.abscur.ru/p/2.html?abs=EGP">EGP (Египетский фунт)</a> - 1.75%, `;
    currencyList.innerHTML = currencyList.innerHTML.slice(0, -2); // Удаляем последнюю запятую
    container.appendChild(currencyList);

});
